name: CI
on:
    push:
        branches:
        - main
    pull_request:
        paths-ignore:
        - 'doc/*.rst'
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    ruff:
        name: Ruff
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v5
        -   uses: actions/setup-python@v6
        -   name: "Main Script"
            run: |
                pip install ruff
                ruff check

    typos:
        name: Typos
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v5
        -   uses: crate-ci/typos@master

    pylint:
        name: Pylint
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v5
        -   name: "Main Script"
            run: |
                curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/prepare-and-run-pylint.sh
                . ./prepare-and-run-pylint.sh "$(basename $GITHUB_REPOSITORY)" examples/*.py test/test_*.py

    basedpyright:
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v5
        -   uses: actions/setup-python@v6
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                EXTRA_INSTALL="basedpyright pytest pyopencl"
                curl -L -O https://tiker.net/ci-support-v0
                . ./ci-support-v0

                build_py_project_in_venv
                basedpyright

    pytest:
        name: Pytest on Py${{ matrix.python-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.12', '3.x']
        steps:
        -   uses: actions/checkout@v5
        -
            uses: actions/setup-python@v6
            with:
                python-version: ${{ matrix.python-version }}
        -   name: "Main Script"
            run: |
                curl -L -O https://tiker.net/ci-support-v0
                . ./ci-support-v0

                build_py_project_in_venv
                test_py_project

    docs:
        name: Documentation
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v5
        -
            uses: actions/setup-python@v6
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                curl -L -O https://tiker.net/ci-support-v0
                . ci-support-v0
                build_py_project_in_venv
                build_docs

    downstream_tests:
        strategy:
            matrix:
                downstream_project: [loopy]
        name: Tests for downstream project ${{ matrix.downstream_project }}
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v5
        -   name: "Main Script"
            env:
                DOWNSTREAM_PROJECT: ${{ matrix.downstream_project }}
            run: |
                curl -L -O https://tiker.net/ci-support-v0
                . ./ci-support-v0
                test_downstream "$DOWNSTREAM_PROJECT"

# vim: sw=4
